#! /bin/env bash

# Copyright (c) 2021-2024 Telxey
# Author: TELXEY (Rax)
# License: MIT
# https://raw.githubusercontent.com/Telxey/Proxmox/main/LICENSE


# Colors Codes
 default=`echo -en "\e[39m"`
 UL="\033[4m"
 BLIK="\033[5m"
 CLE="\033[m"
 BOLD="\033[1m"
 DIM="\e[2m"
 WHT="\033[97m"
 ORG="\033[38;5;208m"
 GRN="\033[1;92m"
 YLW="\033[38;5;184m"
 RED="\033[01;31m"
 BLK="\033[34m"
 DFLT="\033[39m"
 AQUA="\033[36m"
 BLD=$(echo "\033[1")
 LBL=$(echo "\033[38;5;33m")
 YW=$(echo "\033[33m")
 BL=$(echo "\033[36m")
 RD=$(echo "\033[01;31m")
 BGN=$(echo "\033[4;92m")
 GN=$(echo "\033[1;92m")
 DGN=$(echo "\033[32m")
 CL=$(echo "\033[m")
 CM="${GN}✓${CL}"
 CROSS="${RD}✗${CL}"
 BFR="\\r\\033[K"
 HOLD="-"

# This is solid prosgres bar funtion
progress-bar() {
  local duration=${1}


    already_done() { for ((done=0; done<elapsed; done++)); do printf "▇"; done }
    remaining() { for ((remain=elapsed; remain<duration; remain++)); do printf " "; done }
    percentage() { printf "| %s%%" $(( ((elapsed)*100)/(duration)*100/100 )); }
    clean_line() { printf "\r"; }

  for (( elapsed=1; elapsed<=duration; elapsed++ )); do
      already_done; remaining; percentage
      sleep 0.15
      clean_line
  done
  clean_line
}

# This function clear all colors .
msg_clear() {
  local msg="$1"
  echo -e "${BFR} ${msg}${CL}"
}
# This function displays an informational message with a yellow color.
msg_info() {
  local msg="$1"
  echo -ne " ${HOLD} ${YW}${msg}..."
}
# This function displays a success message with a green color.
msg_ok() {
  local msg="$1"
  echo -e "${BFR} ${CM} ${GN}${msg}${CL}"
}
# This function displays an error message with a red color.
msg_error() {
  local msg="$1"
  echo -e "${BFR} ${CROSS} ${RD}${msg}${CL}"
}
# Run as root only
check_root() {
  if [[ "$(id -u)" -ne 0 || $(ps -o comm= -p $PPID) == "sudo" ]]; then
    clear
    msg_error "Please run this script as root."
    echo -e "\nExiting..."
    sleep 2
    exit
  fi
}
if ! [ "$(id -u)" = 0 ]; then
   msg_ok "The script need to be run as root." >&2
   exit 1
fi

if [ "$SUDO_USER" ]; then
    export real_user=$SUDO_USER
else
    real_user=$(whoami)
fi
OUTPUT=$(cat /etc/*release)
OS=$(cat /etc/*-release | grep -Po "(?<=^ID=).+" | sed 's/"//g')
NAME=$(cat /etc/*-release | grep -E "PRETTY_NAME" | cut -d = -f 2 | tr -d '"')
HS=$(hostname)
ARCH=$(uname -m)
LOCAL_IP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
EXT_IP=$(dig @resolver4.opendns.com myip.opendns.com +short)
if echo "$OUTPUT" | grep -q "Orange Pi" ; then
                export  SERVER_OS="Orange Pi"

else

                echo -e "${RED}Unable to detect supported OS...${CLE}"
                echo -e "${WHT}${BOLD}This Install is supported on ${ORG}${BOLD}Orange Pi ${WHT}${BOLD}Distro Only ...${CLE}"
                exit 1
fi

clear
echo -e "${RED}${BOLD}"
cat <<"EOF" 

           ██╗    ██╗ █████╗ ██████╗ ███╗   ██╗██╗ ██████╗
           ██║    ██║██╔══██╗██╔══██╗████╗  ██║██║██╔════╝
           ██║ █╗ ██║███████║██████╔╝██╔██╗ ██║██║██║  ███╗
           ██║███╗██║██╔══██║██╔══██╗██║╚██╗██║██║██║   ██║
           ╚███╔███╔╝██║  ██║██║  ██║██║ ╚████║██║╚██████╔╝
            ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝ ╚═════╝

EOF

echo -e "${CL}"
echo -e "${GN}                   User ${RD} ---> ${WHT}${UL}$(whoami)${CL} ${RD}<---${CL}${GRN} running script${CL}"
echo -e "${GRN}${BOLD}   Supported OS${CLE}${RED} $OS${ORG} $NAME ${LBL}$ARCH  ${GRN}${BOLD}Runimg ${CLE}"
echo -e "${WHT}${BOLD}   ====================================================================${CL}"
echo -e "${LBL}                  DETECTED ${WHT}${UL}$(whoami)${CL} ${LBL} RUN THIS SCRIPT                    ${CL}"
echo -e "${LBL}          PLEASE DONT USE${RED} sudo${LBL}, USE${GRN} su ${CL}${LBL}TO LOGIN TO THE ROOT USER  ${CL}"
echo -e "${LBL}             PLEASE STOP THIS SCRIPT YOU ARE USING SUDO                                        ${CL}"
echo -e "${LBL}           IF YOU ARE USING SUDO SCRIPT FAIL ON NEXT STEP PLEASE                               ${CL}"
echo -e "${WHT}${BOLD}   ====================================================================${CL}"

echo -e "${CL}${WHT}   Hostname${RED}: ${GRN}$HS ${WHT}Local IP${RED}:${GRN} $LOCAL_IP ${WHT} Eternal IP${RED}: ${GRN}$EXT_IP${CL}"
echo -e "${CL}"
#read -r -p "Would you like exit to login as  root now ? ( if you are root hit enter ) <y/N> " prompt
echo -e "${YLW}Would you like exit to login as  root now ? type y or  if you are root hit ${GN}${UL}ENTER${CL}" 
read -r -p "Select Yes or No  <y/N> " prompt
if [[ "${prompt,,}" =~ ^(y|yes)$ ]]; then
    echo -e "${GRN}Run ${WHT}${DIM}${BOLD}${UL}su${CLE}${GRN} for switch to ${WHT}${BOLD}root${CLE}"
    exit 1
fi
read -r -p "Would you like to add set root Password now ?( If no hit enter ) <y/N> " prompt
if [[ "${prompt,,}" =~ ^(y|yes)$ ]]; then
  sudo passwd root
fi
read -r -p "Would you like to change default user --> orangepi <-- Password now ?( If no hit enter ) <y/N> " prompt
if [[ "${prompt,,}" =~ ^(y|yes)$ ]]; then
  sudo passwd orangepi
fi
read -r -p "Would you like set HOSTNAME  now ?( If no hit enter ) <y/N> " prompt
if [[ "${prompt,,}" =~ ^(y|yes)$ ]]; then
read -p "Enter new hostname e.g. armmox : " HOSTNAME
while [[ ! "$HOSTNAME" =~ ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$ ]]
 do
  printf " --->$RED $HOSTNAME $CLE<--- Is NOT an valid HOSTNAME, try again...\n"
  read -p "Enter new hostname e.g.: armmox  : " HOSTNAME
done
hostnamectl set-hostname $HOSTNAME
printf " $WHT New Hostname $RED--->$GRN $HOSTNAME $RED<---$CLE\n"
fi
printf $ORG
progress-bar 75 $CLE; msg_clear

cat <<"EOF"

EOF
#
#
# Start collecting system OS
echo -e "${GRN}${BOLD}Collect some basic information on your system, you appear to be running:${CLE} "
echo -e "${YLW}"
echo -e "          --  OS Name                $(cat /etc/*-release | grep -Po "(?<=^ID=).+" | sed 's/"//g')"
echo -e "          --  Description            $(cat /etc/*-release | grep -E "PRETTY_NAME" | cut -d = -f 2 | tr -d '"')"
echo -e "          --  OS Version release     $(cat /etc/*-release | grep -E "VERSION_ID" | cut -d = -f 2 | tr -d '"')"
echo -e "          --  Code Name              $(cat /etc/*-release | grep -E "VERSION_CODENAME" | cut -d = -f 2 | tr -d '"')"
echo -e "${CLE}"
echo -e "${WHT}${BOLD}    --------------------------------------------------------------------${CL}"
echo -e "${LBL}"
cat <<"EOF"
                  Be patient with the installing setup, 
                 take a few minutes depending on PI model


EOF
msg_info "Cheking root"
sleep 3
check_root
msg_ok "Good root detected loading setup ..."
msg_info "check for updates"
rm -f /etc/apt/sources.list.d/docker.list
apt update &> /dev/null
sleep 3
msg_ok "System Updated"
msg_info "Installing available upgrades"
apt upgrade -y &> /dev/null
msg_ok "upgrades Installed"
msg_info "Perform Full System Upgrade"
apt full-upgrade -y  &>  /dev/null
msg_ok "System Upgraded"
sleep 5
msg_info "instaling Basic Tools"
apt install -y duf btop curl nano gnupg ca-certificates wiringpi &> /dev/null
msg_ok "Basic Tools Installed"
msg_info "stoped and removed unused services and configurations"
systemctl stop docker &> /dev/null
sleep 3
systemctl disable docker &> /dev/null
for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do sudo apt-get remove $pkg; done &> /dev/null
apt autoclean -y &> /dev/null
apt autoremove -y &> /dev/null
msg_ok "system cleanup sucess"

msg_info "Remove autologin"
sed -i -e 's/--autologin orangepi//g' /usr/lib/systemd/system/getty@.service.d/override.conf
sudo systemctl daemon-reload &> /dev/null
msg_ok "autologin Stoped"

msg_info "Adding proxmox ARM64 and aarch64 repos"
curl -s https://mirrors.apqa.cn/proxmox/debian/pveport.gpg | tee /usr/share/keyrings/pveport.gpg &> /dev/null
echo "deb [deb=arm64] https://mirrors.apqa.cn/proxmox/debian/pve bookworm port" | tee  /etc/apt/sources.list.d/pveport.list &> /dev/null
sleep 3
msg_ok "proxmox arm repos added"
msg_info "Updating packages list"
apt update &> /dev/null
msg_ok "System updateted"
msg_info "Instaling PVE Networking tools"
sudo apt install -y ifupdown2 openvswitch-switch grub-efi-arm64 &> /dev/null
msg_ok "iptools instaled"
msg_info "Instaling Postfix"
sudo debconf-set-selections <<< "postfix postfix/main_mailer_type select Local only"
sudo debconf-set-selections <<< "postfix postfix/mailname string $HOSTNAME"
apt install -y postfix &> /dev/null
msg_ok "Postfix instaled"
msg_ok "Start proxmox Instalations"
apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install proxmox-ve open-iscsi pve-edk2-firmware-aarch64 &> /dev/null
msg_ok " proxmox Instaled sucess "
msg_ok " DONE"

printf "
=========================================================================================
                   $GRN     ! INSTALATION COMPLETED ! WAIT ! REBOOT ! $CLE
=========================================================================================

    after reboot the PVE web interface will be reachable here :
      --->  $GRN https://$LOCAL_IP:8006/ $CLE <---

    For External access to PVE interface set route to be reachable here :
      --->  $GRN https://$EXT_IP:8006/ $CLE <---
         
         run ---> $YLW apt upgrade -y $CLE <---

           in a root shell to complete the installation.

\n" 
printf " $GRN Systen Rebooting $CLE \n"
printf  $ORG
progress-bar 100 $RED; msg_clear && reboot
exit
#### EOF ####
