#! /bin/env bash

#sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" &>/dev/null

#wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh &>/dev/null
#bash install.sh
#sleep 3
#rm install.sh
msg_ok "oh my zsh Installed"
msg_info "Configure oh my zsh and Z-Shell"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting &>/dev/null
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions &>/dev/null
msg_info "Enabling Plugins"
mv ~/.zshrc ~/.zshrc.bak
wget https://raw.githubusercontent.com/Telxey/Proxmox/main/system-tools/oh-my-zsh/.zshrc -P ~/ &>/dev/null
msg_ok "Plugins Set"
msg_info "Reload Configurations"
source ~/.zshrc
msg_ok "Installed Z-Shell"
