#!/usr/bin/env bash

# Copyright (c) 2023-2024 TELXEY
# Author: Telxey ( Rax )
# License: MIT
# https://raw.githubusercontent.com/Telxey/Proxmox/main/LICENSE

bash -c "$(wget -qLO - https://raw.githubusercontent.com/Telxey/Proxmox/main/system-tools/Z-Shell/Z-Shell)" &>dev/null \
wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh &>/dev/null \
bash install.sh  && sleep 3 && rm install.sh \
bash  -c "$(wget -qLO - https://raw.githubusercontent.com/Telxey/Proxmox/main/system-tools/Z-Shell/config)"







