#!/usr/bin/env bash

# Copyright (c) 2023-2024 TELXEY
# Author: Telxey ( Rax )
# License: MIT
# https://raw.githubusercontent.com/Telxey/Proxmox/main/LICENSE

WT=$(echo "\033[97m")
OR=$(echo "\033[38;5;208m")
RD=$(echo "\033[01;31m")
YW=$(echo "\033[33m")
GN=$(echo "\033[1;92m")
GRN=$(echo "\033[32m")
CL=$(echo "\033[m")
DM=$(echo "\e[2m")
BLD=$(echo "\033[1m")
BFR="\\r\\033[K"
HOLD="-"
CM="${GN}✓${CL}"
CROSS="${RD}✗${CL}"

msg_error() {
  local msg="$1"
  echo -e "${BFR} ${CROSS} ${RD}${msg}${CL}"
}

echo -e "${RAINBOW}"
cat <<"EOF"

bash -c "$(wget -qLO - https://raw.githubusercontent.com/Telxey/Proxmox/main/system-tools/Z-Shell/Z-Shell)" &>dev/null \
wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh &>/dev/null \
bash install.sh  && sleep 3 && rm install.sh \
bash  -c "$(wget -qLO - https://raw.githubusercontent.com/Telxey/Proxmox/main/system-tools/Z-Shell/config)"







