#!/usr/bin/env bash

# Copyright (c) 2023-2024 TELXEY
# Author: Telxey ( Rax )
# License: MIT
# https://raw.githubusercontent.com/Telxey/Proxmox/main/LICENSE

WT=$(echo "\033[97m")
OR=$(echo "\033[38;5;208m")
RD=$(echo "\033[01;31m")
YW=$(echo "\033[33m")
GN=$(echo "\033[1;92m")
GRN=$(echo "\033[32m")
CL=$(echo "\033[m")
DM=$(echo "\e[2m")
BLD=$(echo "\033[1m")
BFR="\\r\\033[K"
HOLD="-"
CM="${GN}✓${CL}"
CROSS="${RD}✗${CL}"

check_root() {
  if [[ "$(id -u)" -ne 0 || $(ps -o comm= -p $PPID) == "sudo" ]]; then
    clear
    msg_error "Please run this script as root."
    echo -e "\nExiting..."
    sleep 2
    exit
  fi
}

function msg_info() {
  local msg="$1"
  echo -ne " ${HOLD} ${YW}${msg}..."
}

function msg_ok() {
  local msg="$1"
  echo -e "${BFR} ${CM} ${GN}${msg}${CL}"
}

  clear
  echo -e "${BLD}${GRN}"
  cat <<"EOF"


    ░▒█░▄▀░█▀▀░█▀▀▄░█▀▀▄░█▀▀░█░░░░▒█▀▀▄░█░░█▀▀░█▀▀▄░█▀▀▄
    ░▒█▀▄░░█▀▀░█▄▄▀░█░▒█░█▀▀░█░░░░▒█░░░░█░░█▀▀░█▄▄█░█░▒█
    ░▒█░▒█░▀▀▀░▀░▀▀░▀░░▀░▀▀▀░▀▀░░░▒█▄▄▀░▀▀░▀▀▀░▀░░▀░▀░░▀

EOF

echo -e "${CL}${DM}${WT}Author: ${GN}${BLD}TELXEY${CL}"
echo -e "${OR}${BLD}Do you wish to continue removing olds Kernels ?"
echo -e "${WT}For continew press ${GN}${BLD}1 ${WT}${BLD} or  ${WT}For cancel press ${RD}${BLD} 2 ${CL}"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) $@; break;;
        No ) echo -e "${RD}Kernel Cleaner Canceled${CL}";  exit;;
    esac
done

current_kernel=$(uname -r)
available_kernels=$(dpkg --list | grep 'kernel-.*-pve' | awk '{print $2}' | grep -v "$current_kernel" | sort -V)

whiptail --backtitle "Proxmox Scripts" --title "Proxmox VE Kernel Clean" --yesno "This will Clean Unused Kernel Images, USE AT YOUR OWN RISK. Proceed?" 10 68 || exit
if [ -z "$available_kernels" ]; then
  whiptail --backtitle "Proxmox VE Helper Scripts" --title "No Old Kernels" --msgbox "It appears there are no old Kernels on your system. \nCurrent kernel ($current_kernel)." 10 68
  echo "Exiting..."
  sleep 2
  clear
  exit
fi
  KERNEL_MENU=()
  MSG_MAX_LENGTH=0
while read -r TAG ITEM; do
  OFFSET=2
  ((${#ITEM} + OFFSET > MSG_MAX_LENGTH)) && MSG_MAX_LENGTH=${#ITEM}+OFFSET
  KERNEL_MENU+=("$TAG" "$ITEM " "OFF")
done < <(echo "$available_kernels")

remove_kernels=$(whiptail --backtitle "Proxmox Scripts" --title "Current Kernel $current_kernel" --checklist "\nSelect Kernels to remove:\n" 16 $((MSG_MAX_LENGTH + 58)) 6 "${KERNEL_MENU[@]}" 3>&1 1>&2 2>&3 | tr -d '"') || exit
[ -z "$remove_kernels" ] && {
  whiptail --backtitle "Proxmox Scripts" --title "No Kernel Selected" --msgbox "It appears that no Kernel was selected" 10 68
  echo "Exiting..."
  sleep 2
  clear
  exit
}
whiptail --backtitle "Proxmox Scripts" --title "Remove Unused Kernels" --yesno "Would you like to remove the $(echo $remove_kernels | awk '{print NF}') previously selected Kernels?" 10 68 || exit

msg_info "Removing ${CL}${RD}$(echo $remove_kernels | awk '{print NF}') ${CL}${YW}old Kernels${CL}"
/usr/bin/apt purge -y $remove_kernels >/dev/null 2>&1
msg_ok "Successfully Removed Kernels"

msg_info "Updating GRUB"
/usr/sbin/update-grub >/dev/null 2>&1
msg_ok "Successfully Updated GRUB"
msg_info "Exiting"
sleep 2
msg_ok "Finished"
