#!/usr/bin/env bash

# Copyright (c) 2023-2024 TELXEY
# Author: Telxey ( Rax )
# License: MIT
# https://raw.githubusercontent.com/Telxey/Proxmox/main/LICENSE

WT=$(echo "\033[97m")
LBL=$(echo "\033[38;5;33m")
OR=$(echo "\033[38;5;208m")
RD=$(echo "\033[01;31m")
YW=$(echo "\033[33m")
GN=$(echo "\033[1;92m")
GRN=$(echo "\033[32m")
CL=$(echo "\033[m")
DM=$(echo "\e[2m")
BLD=$(echo "\033[1m")
BFR="\\r\\033[K"
HOLD="-"
CM="${GN}✓${CL}"
CROSS="${RD}✗${CL}"


function msg_info() {
  local msg="$1"
  echo -ne " ${HOLD} ${YW}${msg}..."
}

function msg_ok() {
  local msg="$1"
  echo -e "${BFR} ${CM} ${GN}${msg}${CL}"
}


msg_info "Installing Z-Shell "
apt update &>/dev/null
apt install -y zsh &>/dev/null
apt install -y git &>/dev/null
msg_ok "Z-Shell Installed"
msg_info "Installing Extra Features (Patience)"
apt  install -y figlet neofetch toilet btop duf htop &>/dev/null
msg_ok "Extras Installed"
chsh -s $(which zsh)
echo -e "${YW}${BLD}Z--Shell Version and locations (expected) ${RD}---> ${GN}/usr/bin/zsh ${LBL}"
zsh --version
echo -e "${GN}" $SHELL
echo -e "${CL}"
sleep 10
msg_info "Installing Oh my zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" &>/dev/null

#wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh &>/dev/null
#bash install.sh
#rm install.sh
msg_ok "oh my zsh Installed"
msg_info "Configure oh my zsh and Z-Shell"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting &>/dev/null
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions &>/dev/null
msg_info "Enabling Plugins"
mv ~/.zshrc ~/.zshrc.bak
wget https://raw.githubusercontent.com/Telxey/Proxmox/main/system-tools/oh-my-zsh/.zshrc -P ~/ &>/dev/null
msg_ok "Plugins Set"
msg_info "Reload Configurations"
source ~/.zshrc
msg_ok "Installed Z-Shell"
